### PR TITLE
Fix #208 - O.Invert doesn't work for interfaces (just for types)

### LINKED ISSUE #208: O.Invert doesn't work for interfaces (just for types)
#### Describe the bug
O.Invert doesn't work for interfaces (just for types)

#### Reproduce the bug
```ts
type O_INVERT = {
    A: 'Av';
};

type INVERT_O = {
    Av: 'A';
};

interface O_INVERT1 {
    A: 'Av';
}

interface INVERT1_O {
    Av: 'A';
}

checks([
    check<O.Invert<O_INVERT>, INVERT_O, Test.Pass>(), // PASSES
    check<O.Invert<O_INVERT1>, INVERT1_O, Test.Pass>(), // FAILS
])
```

#### Expected behavior
Both tests in the example should pass

#### Possible Solution
The reason for this issue is explained [here](https://stackoverflow.com/a/64627401/2242402):
> Object types have an implicit index signature, but interfaces don't (for safety reasons), so they don't extend an index type.

#### Additional context
Happens on the latest versions of this library and typescript.

### PR DESCRIPTION
**Pull request by regevbr**
## 🎁 Pull Request

* [x] Used a clear / meaningful title for this pull request
* [x] Tested the changes in your own code (on your projects)
* [x] Added / Edited tests to reflect changes (`tests` folder)
* [x] Have read the **Contributing** part of the **Readme**
* [x] Passed `npm test`

#### Fixes
#208

#### Why have you made changes?
To fix the issue so O.Invert can support interfaces as well. Basically a revert of [73b8948e](https://github.com/millsp/ts-toolbelt/commit/73b8948ea1d49e05ae8c63b17926eda4cb04e9bb)  which caused the issue to appear.

#### What changes have you made?
I have restricted the type space of the keys of the Record constraint so it will not force an index signature to exist on the generic type O
Bonus - I also fixed the PR template to point to the correct tests dir :-)

#### What tests have you updated?
* tested this in `tests/Object.ts` under the INVERT section (line 426)

#### Is there any breaking changes?
* [ ] Yes, I changed the public API & documented it
* [ ] Yes, I changed existing tests
* [ ] No,  I added to the public API & documented it
* [x] No,  I added to the existing tests
* [ ] I don't know

### CODE REVIEW

**Comment by regevbr** [comment]
@millsp can you please CR?

File: sources/Object/Invert.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export type _Invert<O extends Record<Key, Key>> =
  * type test1 = O.Invert<O>
  * ```
  */
-export type Invert<O extends Record<Key, Key>> =
+export type Invert<O extends Record<keyof O, Key>> =
```
Comment (millsp) [inline sources/Object/Invert.ts:44]: I don't think we should use `keyof` here because it will break on unions. Is it this that caused the invert not to work on interfaces?

Comment (millsp) [reply sources/Object/Invert.ts:44]: Maybe it won't break, would you be able to look if we've got tests with unions on this utility. It's certainly the tests that lack the most.

Comment (millsp) [reply sources/Object/Invert.ts:44]: On an union of two objects with different properties basically.

Comment (regevbr) [reply sources/Object/Invert.ts:44]: @millsp check out the new tests I just added. don't seem to break anything. The commit the removed the `key of` part was the one that caused the break...

**Comment by regevbr** [comment]
@millsp can you please CR?

**Comment by millsp** [comment]
Thanks!
